# Generated by Django 5.2.18 on 2026-10-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('tilt_deg', models.FloatField(blank=True, null=True)),
                ('azimuth_deg', models.FloatField(blank=True, null=True)),
                ('kwp_dc', models.FloatField(default=0)),
                ('ac_kw', models.FloatField(default=0)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('data_policy', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RunMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('n_days', models.IntegerField(default=0)),
                ('soiling_ratio', models.FloatField(default=1.0)),
                ('factors_json', models.JSONField(default=dict)),
                ('totals_json', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runmeta', to='dashboard.site')),
            ],
        ),
        migrations.CreateModel(
            name='OutageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.IntegerField()),
                ('est_lost_kwh', models.FloatField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.site')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('site', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='LossRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('segment', models.CharField(blank=True, max_length=10)),
                ('factor', models.FloatField(default=1.0)),
                ('expected', models.FloatField()),
                ('aoi', models.FloatField(default=0)),
                ('temp', models.FloatField(default=0)),
                ('soiling', models.FloatField(default=0)),
                ('dc_cable', models.FloatField(default=0)),
                ('inv_conv', models.FloatField(default=0)),
                ('clip', models.FloatField(default=0)),
                ('ac_cable', models.FloatField(default=0)),
                ('predicted', models.FloatField(default=0)),
                ('actual', models.FloatField(default=0)),
                ('avail', models.FloatField(default=0)),
                ('missing', models.FloatField(default=0)),
                ('unexplained', models.FloatField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss', to='dashboard.site')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('site', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('generated_kwh', models.FloatField()),
                ('peak_kw', models.FloatField(blank=True, null=True)),
                ('peak_time', models.CharField(blank=True, max_length=20)),
                ('conditions', models.CharField(blank=True, max_length=100)),
                ('temp_text', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('flags', models.CharField(blank=True, max_length=100)),
                ('ghi_kwh_m2', models.FloatField(blank=True, null=True)),
                ('tmean_c', models.FloatField(blank=True, null=True)),
                ('precip_mm', models.FloatField(blank=True, null=True)),
                ('cloud_pct', models.FloatField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='dashboard.site')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['site', '-date'], name='dashboard_d_site_id_cb43f4_idx')],
                'unique_together': {('site', 'date')},
            },
        ),
    ]
