# Generated by Django 5.2.18 on 2026-10-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='pvoutput_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='pvoutput_system_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
