# Generated by Django 5.2.18 on 2026-10-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_site_pvoutput_api_key_site_pvoutput_system_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(default='wash', max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='dashboard.site')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('site', 'date')},
            },
        ),
    ]
